// Validation suite: run TS ports against RRI-CUI/Project/solo30s sample data and
// compare with the reference outputs generated by the original Fortran tools.
import { readFileSync } from 'node:fs'
import { parseAsciiGrid } from '../src/core/grid.ts'
import { parseRain } from '../src/core/rain.ts'
import { parseRriInput, serializeRriInput } from '../src/core/rriInput.ts'
import { demAdjust } from '../src/tools/demAdjust.ts'
import { parseGaugeFile, rainThiessen } from '../src/tools/rainThiessen.ts'
import { rainBasin } from '../src/tools/rainBasin.ts'
import { makeRiver } from '../src/tools/makeRiver.ts'
import { flowDirection } from '../src/tools/flowDirection.ts'
import { scaleUp } from '../src/tools/scaleUp.ts'
import { calcTc } from '../src/tools/calcTc.ts'
import { calcZone } from '../src/tools/calcZone.ts'
import { evalHydro } from '../src/tools/evalHydro.ts'
import { section, parseXZ } from '../src/tools/section.ts'

const proj = new URL('../../RRI-CUI/Project/solo30s/', import.meta.url)
const etc = new URL('../../RRI-CUI/etc/', import.meta.url)
const read = (rel: string, base = proj) => readFileSync(new URL(rel, base), 'utf8')

let pass = 0
let fail = 0
function check(name: string, ok: boolean, detail = '') {
  if (ok) { pass++; console.log(`  PASS ${name}`) }
  else { fail++; console.log(`  FAIL ${name} ${detail}`) }
}

// ---------- shared inputs ----------
const dem = parseAsciiGrid(read('topo/dem.txt'))
const dir = parseAsciiGrid(read('topo/dir.txt'))
const acc = parseAsciiGrid(read('topo/acc.txt'))
const adem = parseAsciiGrid(read('topo/adem.txt'))
const adir = parseAsciiGrid(read('topo/adir.txt'))

// ---------- demAdjust ----------
{
  console.log('demAdjust2:')
  const r = demAdjust(dem, dir, acc)
  let maxd = 0
  for (let k = 0; k < r.adem.data.length; k++) {
    const d = Math.abs(r.adem.data[k] - adem.data[k])
    if (d > maxd) maxd = d
  }
  check('adem matches reference', maxd < 1e-3, `maxdiff=${maxd}`)
  let dirDiff = 0
  for (let k = 0; k < r.adir.data.length; k++) if (r.adir.data[k] !== adir.data[k]) dirDiff++
  check('adir matches reference', dirDiff === 0, `${dirDiff} cells differ`)
}

// ---------- rainThiessen ----------
{
  console.log('rainThiessen:')
  const gauge = parseGaugeFile(read('rain/gauge_1d.txt'))
  const r = rainThiessen(gauge, {
    divide: 24, ncols: 336, nrows: 204, xll: 110.2, yll: -8.3, cellsize: 0.0083333333333333,
  })
  const ref = parseRain(read('rain/rain.dat'))
  check('block count', r.rain.frames.length === ref.frames.length,
    `got ${r.rain.frames.length}, ref ${ref.frames.length}`)
  check('times match', r.rain.times.every((t, i) => t === ref.times[i]))
  let maxd = 0
  const nT = Math.min(r.rain.frames.length, ref.frames.length)
  for (let t = 0; t < nT; t++) {
    for (let k = 0; k < ref.frames[t].length; k++) {
      const d = Math.abs(r.rain.frames[t][k] - ref.frames[t][k])
      if (d > maxd) maxd = d
    }
  }
  check('rain values match (<=0.002 mm/h, output rounding)', maxd <= 2.001e-3, `maxdiff=${maxd}`)
  const refMap = parseAsciiGrid(read('rain/gauge_map.txt'))
  let mapDiff = 0
  for (let k = 0; k < refMap.data.length; k++) if (refMap.data[k] !== r.map.data[k]) mapDiff++
  check('gauge map matches', mapDiff === 0, `${mapDiff} cells differ`)
}

// ---------- rainBasin ----------
{
  console.log('rainBasin:')
  const rain = parseRain(read('rain/rain.dat'))
  const r = rainBasin(rain, adem, {
    xllRain: 110.2, yllRain: -8.3, cellsizeRainX: 0.00833333, cellsizeRainY: 0.00833333,
  })
  const refHyeto = read('rain/rain_hyeto.txt').trim().split(/\r?\n/).map((l) => l.trim().split(/\s+/).map(Number))
  const refCum = read('rain/rain_cum.txt').trim().split(/\r?\n/).map((l) => l.trim().split(/\s+/).map(Number))
  let maxH = 0
  for (let t = 0; t < Math.min(refHyeto.length, r.hyeto.length); t++) {
    maxH = Math.max(maxH, Math.abs(refHyeto[t][1] - r.hyeto[t]))
  }
  check('hyetograph matches', refHyeto.length === r.hyeto.length && maxH < 1e-4, `maxdiff=${maxH}`)
  let maxC = 0
  for (let t = 0; t < Math.min(refCum.length, r.cum.length); t++) {
    maxC = Math.max(maxC, Math.abs(refCum[t][1] - r.cum[t]))
  }
  check('cumulative matches', maxC < 1e-3, `maxdiff=${maxC}`)
  const refDist = parseAsciiGrid(read('rain/rain_dist.txt'))
  let maxD = 0
  for (let k = 0; k < refDist.data.length; k++) {
    if (refDist.data[k] < -100) continue
    maxD = Math.max(maxD, Math.abs(refDist.data[k] - r.dist.data[k]))
  }
  check('distribution matches', maxD < 1e-3, `maxdiff=${maxD}`)
}

// ---------- makeRiver (parameters from solo30s RRI_Input.txt) ----------
{
  console.log('makeRiver3:')
  const accMod = parseAsciiGrid(read('topo/acc_mod.txt'))
  const dirMod = parseAsciiGrid(read('topo/dir_mod.txt'))
  const r = makeRiver(adem, dirMod, accMod, {
    utm: false, thresh: 100, widthC: 5, widthS: 0.35, depthC: 0.95, depthS: 0.2,
    heightParam: 0, heightLimit: 20,
  })
  // sanity: river cells only where acc>thresh; width monotone in area
  let ok = true
  for (let k = 0; k < r.width.data.length; k++) {
    const isRiv = accMod.data[k] > 100 && adem.data[k] > -100
    if (isRiv !== r.width.data[k] > 0) { ok = false; break }
  }
  check('river mask consistent with acc threshold', ok)
  const stats = r.width.data.filter((v) => v > 0)
  check('widths positive and bounded', stats.length > 0 && Math.max(...stats) < 5000)
}

// ---------- flowDirection (modern) ----------
{
  console.log('flowDirection:')
  const riv = parseAsciiGrid(read('riv/riv_mod.txt'))
  const r = flowDirection(dem, riv)
  // Every domain cell must drain to an outlet: acc at outlets ~ upstream count
  let domainCells = 0
  for (let k = 0; k < dem.data.length; k++) if (dem.data[k] >= -100) domainCells++
  let accSumAtOutlets = 0
  for (const o of r.outlets) accSumAtOutlets += r.acc.data[(o.i - 1) * dem.ncols + (o.j - 1)]
  check('all cells drain to outlets', accSumAtOutlets + r.maskedCells === domainCells,
    `outletAcc=${accSumAtOutlets} masked=${r.maskedCells} domain=${domainCells}`)
  // no cycles: acc computed for every resolved cell (indeg queue exhausted) — spot check acc>=1
  let minAcc = Infinity
  for (let k = 0; k < r.acc.data.length; k++) {
    if (r.dir.data[k] >= 0 && r.acc.data[k] < minAcc) minAcc = r.acc.data[k]
  }
  check('acc >= 1 everywhere in network', minAcc >= 1, `minAcc=${minAcc}`)
  // rivers must flow along rivers: for every riv==100 cell, downstream cell is also river (or outlet)
  let rivOk = true
  for (let k = 0; k < riv.data.length; k++) {
    if (riv.data[k] !== 100) continue
    const code = r.dir.data[k]
    if (code <= 0) continue
    const off = { 1: [0, 1], 2: [1, 1], 4: [1, 0], 8: [1, -1], 16: [0, -1], 32: [-1, -1], 64: [-1, 0], 128: [-1, 1] }[code as 1]!
    const kn = (Math.floor(k / dem.ncols) + off[0]) * dem.ncols + (k % dem.ncols) + off[1]
    if (!(riv.data[kn] === 100 || riv.data[kn] === 0 ||
          [1, 2, 4, 8, 16, 32, 64, 128].includes(riv.data[kn]))) { rivOk = false; break }
  }
  check('river cells drain along river network', rivOk)
}

// ---------- scaleUp ----------
{
  console.log('scaleUp:')
  const r = scaleUp(adem, adir, acc, 3)
  check('dims', r.dem2.ncols === 112 && r.dem2.nrows === 68)
  check('cellsize x3', Math.abs(r.dem2.cellsize - dem.cellsize * 3) < 1e-12)
  // mass conservation-ish: max acc2 should be near maxAcc/9
  const maxAcc = Math.max(...Array.from(acc.data).filter((v) => v > -100))
  const maxAcc2 = Math.max(...Array.from(r.acc2.data).filter((v) => v > -100))
  check('acc magnitude plausible', maxAcc2 > (maxAcc / 9) * 0.5 && maxAcc2 < (maxAcc / 9) * 2,
    `maxAcc2=${maxAcc2} expected~${Math.round(maxAcc / 9)}`)
}

// ---------- calcTc / calcZone ----------
{
  console.log('calcTc / calcZone:')
  const accMod = parseAsciiGrid(read('topo/acc_mod.txt'))
  const dirMod = parseAsciiGrid(read('topo/dir_mod.txt'))
  const tc = calcTc(adem, dirMod, accMod, null, {
    utm: false, manning: true, rain: 10, nr: 0.03, ns: 0.3, ka: 0.1,
  })
  let tcMax = 0
  let tcNeg = false
  for (let k = 0; k < tc.tc.data.length; k++) {
    const v = tc.tc.data[k]
    if (v < -100) continue
    if (v < 0) tcNeg = true
    if (v > tcMax) tcMax = v
  }
  check('tc nonnegative, plausible range', !tcNeg && tcMax > 1 && tcMax < 2000, `max=${tcMax.toFixed(1)}h`)

  const z = calcZone(adem, dirMod, accMod, { utm: false, div: 20, accThresh: 20, rivRatio: 0.1 })
  const counts = new Map<number, number>()
  for (let k = 0; k < z.zone.data.length; k++) {
    const v = z.zone.data[k]
    if (v > 0) counts.set(v, (counts.get(v) ?? 0) + 1)
  }
  const sizes = [...counts.values()]
  check('20 zones, near-equal sizes', counts.size === 20 && Math.max(...sizes) - Math.min(...sizes) <= 2,
    `zones=${counts.size} sizes ${Math.min(...sizes)}..${Math.max(...sizes)}`)
}

// ---------- evalHydro ----------
{
  console.log('evalHydro:')
  const obs = [1, 3, 8, 15, 10, 6, 4, 2]
  const m1 = evalHydro(obs, obs)
  check('perfect sim: NSE=1 KGE=1 RMSE=0', Math.abs(m1.nse - 1) < 1e-12 && Math.abs(m1.kge - 1) < 1e-12 && m1.rmse === 0)
  const m2 = evalHydro(obs, obs.map((v) => v * 1.2))
  check('biased sim: PBIAS=20%', Math.abs(m2.pbias - 20) < 1e-9, `pbias=${m2.pbias}`)
}

// ---------- section (against etc/section reference output) ----------
{
  console.log('section:')
  const pts = parseXZ(read('section/CS99C2.txt', etc))
  const r = section(pts, { nsRiver: 0.03, div: 100, datum: 25, startIdx: 1, endIdx: 30 })
  const ref = read('section/sec_000001.txt', etc).trim().split(/\r?\n/).map((l) => l.trim().split(/\s+/).map(Number))
  const [refDiv, refDepth, refHeight] = ref[0]
  check('header (div, depth, height)', refDiv === 100 && Math.abs(refDepth - r.depth) < 1e-4 && Math.abs(refHeight - r.height) < 1e-4,
    `got d=${r.depth.toFixed(5)} h=${r.height.toFixed(5)}, ref d=${refDepth} h=${refHeight}`)
  let maxd = 0
  for (let j = 0; j < 100; j++) {
    const [d, peri, b] = ref[j + 1]
    maxd = Math.max(maxd, Math.abs(d - r.table[j].depth), Math.abs(peri - r.table[j].peri), Math.abs(b - r.table[j].width))
  }
  check('table matches reference', maxd < 1e-3, `maxdiff=${maxd}`)
}

// ---------- RRI_Input round trip ----------
{
  console.log('RRI_Input:')
  const text = read('RRI_Input.txt')
  const r = parseRriInput(text)
  check('parse solo30s', r.lasth === 360 && r.dt === 600 && r.outnum === 96 &&
    r.rainfile === './rain/rain.dat' && r.nsRiver === 0.03 && r.rivThresh === 100 &&
    r.widthParamC === 5 && r.locationFile === './location.txt' &&
    r.outswitch.join(',') === '1,1,0,1,0,0,0,0,0,1')
  const r2 = parseRriInput(serializeRriInput(r))
  const same = JSON.stringify(r) === JSON.stringify({ ...r2, version: r.version })
  check('round trip stable', same)
}

console.log(`\n${pass} passed, ${fail} failed`)
process.exit(fail > 0 ? 1 : 0)
